# Generated by Django 5.1.1 on 2024-10-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Residencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.promotor')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '1 - Pobre'), (2, '2 - Regular'), (3, '3 - Bueno'), (4, '4 - Muy Bueno'), (5, '5 - Excelente')])),
                ('comentario', models.TextField()),
                ('hashtags', models.CharField(help_text='Agrega hashtags separados por comas', max_length=255)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('residencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.residencial')),
            ],
        ),
    ]
